export const items = [
  {
    id: 1,
    categoryName: 'Authentication',
    description: 'Login and Registration forms',
    handle: 'authentication',
    label: 'Go to authentication components',
    searchTerms: [
      'login',
      'register',
      'authentication',
      'component',
      'form',
      'oauth',
      'oauth2',
      'sign in',
      'log in',
      'user',
      'access',
      'account',
      'sign up',
      'create',
      'join',
      'secure',
      'security',
      'username',
      'password',
      'email',
      'validation',
      'identity',
      '2fa',
      'two-factor',
      'social media',
      'captcha'
    ]
  },
  {
    id: 2,
    categoryName: 'Lists',
    description: 'User events, activity feeds, and organization',
    handle: 'lists',
    label: 'Go to list components',
    searchTerms: [
      'lists',
      'itemized',
      'bulleted',
      'feeds',
      'activity',
      'user',
      'events',
      'numbered',
      'unordered',
      'ordered',
      'expandable',
      'tree',
      'check',
      'checklist',
      'dropdown',
      'notifications'
    ]
  },
  {
    id: 3,
    categoryName: 'Dashboards',
    description: 'A power-packed interface to view stats in one place',
    handle: 'dashboards',
    label: 'Go to dashboard components',
    searchTerms: [
      'widgets',
      'cards',
      'panels',
      'charts',
      'graphs',
      'gauges',
      'metrics',
      'kpis',
      'key performance indicators',
      'tiles',
      'tables',
      'lists',
      'notifications',
      'alerts',
      'tabs',
      'tooltips',
      'charts',
      'progress bars',
      'sliders',
      'data',
      'visualization',
      'dashlets',
      'reports',
      'maps',
      'timelines',
      'calendars'
    ]
  },
  {
    id: 4,
    categoryName: 'Profiles',
    description: 'User & Admin Profiles, displaying information and settings',
    handle: 'profiles',
    label: 'Go to profile components',
    searchTerms: [
      'profile',
      'admin',
      'name',
      'username',
      'information',
      'settings',
      'biography',
      'contact information',
      'email',
      'avatar',
      'privacy',
      'security',
      'update',
      'history',
      'activity',
      'friends',
      'favorites',
      'logout',
      'preferences'
    ]
  },
  {
    id: 5,
    categoryName: 'Products',
    description: 'Categories, galleries, checkout & more',
    handle: 'products',
    label: 'Go to product components',
    searchTerms: [
      'products',
      'galleries',
      'categories',
      'checkout',
      'cards',
      'listings',
      'sliders',
      'carousels',
      'filters',
      'reviews',
      'ratings',
      'prices',
      'descriptions',
      'variants',
      'options',
      'images',
      'thumbnails',
      'specifications',
      'specs',
      'comparison',
      'recommendations',
      'suggestions',
      'badges',
      'labels',
      'search',
      'sorting'
    ]
  },
  {
    id: 6,
    categoryName: 'Calls To Action',
    description: 'Pop-outs and section components to promote user engagement',
    handle: 'call-to-action',
    label: 'Go to call to action components',
    searchTerms: [
      'button',
      'call to action',
      'calls',
      'actions',
      'buy now',
      'join us',
      'join now',
      'download',
      'get started',
      'subscribe',
      'discover',
      'explore',
      'contact us',
      'reserve',
      'book now',
      'request'
    ]
  },
  {
    id: 7,
    categoryName: 'Marketing',
    description: 'Lead generation, newsletters, testimonials, & more',
    handle: 'marketing',
    label: 'Go to marketing components',
    searchTerms: [
      'lead generation',
      'newsletters',
      'testimonials',
      'marketing',
      'landing page',
      'conversions',
      'reviews',
      'countdowns',
      'promotions',
      'pop ups',
      'pop-ups',
      'banner ads',
      'integration',
      'subscriptions',
      'upsell',
      'cross-sell',
      'cross sell',
      'pricing tiers'
    ]
  },
  {
    id: 8,
    categoryName: 'Menus',
    description: 'Navigation and other menus',
    handle: 'menus',
    label: 'Go to menu components',
    searchTerms: [
      'navigation',
      'menus',
      'dropdowns',
      'hamburger',
      'sidebars',
      'mega menus',
      'responsive',
      'submenus',
      'flyouts',
      'vertical',
      'horizontal',
      'accordions',
      'tabbed',
      'contextual',
      'off-canvas',
      'nested',
      'bars',
      'burger',
      'links',
      'icons'
    ]
  }
];

type ElementType<T extends ReadonlyArray<unknown>> = T extends ReadonlyArray<
  infer ElementType
>
  ? ElementType
  : never;
export type CategoryItem = ElementType<typeof items>;

export default items;
